---
--- Generated by Luanalysis
--- Created by 范大晨.
--- DateTime: 2022/11/16 11:18
---

-- 订单id
local varcharId=ARGV[1]
-- 用户id
local userId=ARGV[2]

--库存key
local varcharKey="seckill:stock:"..varcharId

--订单Key
local orderKey="seckill:order:"..varcharId

--判断库存是否充足
if (tonumber(redis.call("get",varcharKey))<=0) then
    return 1
end

--判断用户是否下单
if (redis.call("SISMEMBER",orderKey,userId)==1) then
    return 2
end

--扣减库存
redis.call("INCRBY",varcharKey,-1)
redis.call("SADD",orderKey,userId)
return 0
